### ISSUE TITLE
strange behavior with item qualities for ore

### ISSUE THREAD

**Issue by Kimab** [Centias/BankItems#14]
hey there, i just noticed and i dont know how long its happening. here are some pictures:
all tested with and without addons beside bankitems. and approved by my sister, she got this too

![image](https://user-images.githubusercontent.com/21992837/229793687-9e6fb316-35d2-499f-8879-27185e490483.png)
thats for serevite ore, mouse on tier 2

![image](https://user-images.githubusercontent.com/21992837/229793959-c4700dc8-50ef-4169-8fd1-821c5400edad.png)
and thats for serevite or, mouse on tier 3

thats also happening for draconium ore but **NOT** for khazgorite ore
tested it for herbs and leather too, it seems they work completely fine

let me know if you need more info

cheers

**Comment by Kimab** [comment]
i also get 
`11x BankItems/BankItems.lua:4361: attempt to index local 'theBag' (a nil value)`
while making crafting oder stuff

**Comment by Centias** [comment]
I don't really know the how or the why, but for some reason all of the item IDs for ore got shuffled around. They used to all be logically right next to each other in sequence, like 123450 -> 123451 -> 123452 (not the actual IDs) but now they all got shuffled around, breaking the logic I had used.

Serevite Ore rank 1 - 190395
Serevite Ore rank 2 - 190396 (at least these two stayed in order, so they still play nice together)
Serevite Ore rank 3 - 190394 ( ???? I have no idea why this suddenly got moved to below the other two )

Draconium Ore rank 1 - 189143
Draconium Ore rank 2 - 188658
Draconium Ore rank 3 - 190311
These 3 make no sense, they're all over the place.

I'll see if I can get this sorted out over the weekend, because clearly my logic isn't working right now for just these weird cases.

For the second bug, any further detail would be helpful. I haven't seen it happen, but I may have just missed it hiding in BugSack.

**Comment by Kimab** [comment]
Take your time! i noticed the strange IDs also, but i thought they were the original one. crazy stuff...
idk what further details i can provide - it happens sometimes, not always. i will look out in which situations exactly it happens and provide all i can get to you
thanks again and please; take your time! its not like something isnt working at all :)

**Comment by Kimab** [comment]
`34x BankItems/BankItems.lua:4361: attempt to index local 'theBag' (a nil value)`
just happened again - was making a personal order for my sister for an [Empty Soul Cage](https://www.wowhead.com/item=200938/empty-soul-cage) 
duration 2 days, 1 silver commission
i then tried disabling addons but the error didnt occured a second time :/

**Comment by Centias** [comment]
Here's something I managed to throw together tonight that should fix the ore situation. Give it a try and if that part seems to be in order I'll get an update put together with it.

[BankItems.zip](https://github.com/Centias/BankItems/files/11279846/BankItems.zip)

I still have no idea about the error because I haven't caught the error myself. I tried intentionally sending myself a crafting order with none of the reagents included, then left all my material in the bank thinking maybe it had something to do with trying to update the bank, but got no error.

I think the quality icon showing up on random things is actually just a problem in the game. It seems to happen with my mail a lot.

**Comment by Kimab** [comment]
thanks for your work!
i tried the file and it works the same; serevite is 1&2 together, 3 solo and draconium are all 3 solo. 
the error is not much to worry about... bugsack catches an error, but everything works totally fine.

tell me if i can help more :)

**Comment by Centias** [comment]
Hmm, not sure why it's working for me but not for you then. 
![image](https://user-images.githubusercontent.com/62023588/233506922-5c927d31-59e4-42de-aea5-d4f1826718ff.png)

Draconium has 2 & 3 together, I actually just don't have any 1's right now.
![image](https://user-images.githubusercontent.com/62023588/233507025-f44d0f55-f234-4f23-a997-8a1a0c38ca7e.png)

**Comment by Centias** [comment]
I'm possibly an idiot and just realized I basically came up with a solution that only works for English, and you posted an image with item names in another language. I'll have to figure out how I can adapt it across languages or something.

**Comment by Kimab** [comment]
hehehe
sorry for that much work... but there is no other addon that works like BI in terms of qualities. its so handy you see all qualities in one view
thanks and take your time :)

**Comment by Centias** [comment]
Take 2, I think this should work regardless of language :
[BankItems.zip](https://github.com/Centias/BankItems/files/11299886/BankItems.zip)

**Comment by Kimab** [comment]
take 2 works flawless =) thank you SO much! i missed that a lot.
thousand thanks <3
