### ISSUE TITLE
Reagent bank content wipe at crafting

### ISSUE THREAD

**Issue by madar2252** [Centias/BankItems#5]
I tested this with alchemy. If I have some materials only in the reagent bank, then I go craft something with that stuff, the addon wiping the content of the reagent bank. If the items in my backpack, it has no issue. I guess it's trying to update the reagent bank, and failing?

**Comment by GTSavvy** [comment]
It seems like the addon was relying on the fact that it could query the Reagent Bank information at any time (not just when bank tabs are open), but for some reason that isn't working anymore (API change? loss of feature? Not sure). 

You can get the correct totals by setting the BankItems_SaveReagentBank function to only update when the bank is open, but the removed item count goes against the bank and not the reagent bank if that's the only change, so more testing is needed...

**Comment by Centias** [comment]
Trying to get a better understanding of this issue. 

Are you saying the Reagent Bank stored info gets erased? Because I'm not seeing that happening.

Are you saying the material gets removed from the slot when you select it for crafting something? Because I think that's Blizzard's fuck up and I put in a bug report about it. You are **supposed** to be able to craft with all reagents from your bank, but some of the new crafting doesn't play nicely with that.

**Comment by GTSavvy** [comment]
I was able to confirm the observation myself with the current BankItems build. The issue seems to be that the current build relies on the fact that reagent bank information could be queried at any time (even when your character did not have the bank currently open), and that's no longer the case. So, when BankItems tries to call GetContainerInfo(-3,x), it gets back a null table and the BankItems ReagentBank cache gets completely cleared. If your character is currently at the bank and has it open, then the GetContainerInfo will work as previously and it is not broken.

I can prevent the ReagentBank wipe by changing 'BankItems_SaveReagentBank' to only run when the Bank is currently open, but then the addon 'removes' the items from the Bank count instead of the ReagentBank count and the ReagentBank inventory becomes stale and the Bank count becomes negative.

I'm not totally certain if removal of this query was intended (the WoW UI Addon discord seems to think it is intentional), but if it is not a bug then it seems like BankItems will need to update it's treatment of the ReagentBank contents to be manually updated in a cache like the regular Bank contents are.

**Comment by Centias** [comment]
Does it only trigger the call to GetContainerInfo(-3,x) when the craft uses a reagent from the reagent bank? I'm having trouble making it happen.

If you think you have a good solution for it, I'm open to it. I'm just haven't been able to reproduce the issue to see why it happens.

**Comment by GTSavvy** [comment]
I can make it happen consistently on my tailor using netherweave cloth and just making bolts. From what I've seen, crafting that uses items from the reagent bank will trigger an event on this line:

https://github.com/Centias/BankItems/blob/8c26ee910fd3709f5a596fda17fd679a85bca90f/BankItems.lua#L988

This sets 'bagsToUpdate.rbank' to 'true', which in the BankItems_UpdateFrame_OnUpdate() function will trigger a BankItems_SaveReagentBank() call

https://github.com/Centias/BankItems/blob/8c26ee910fd3709f5a596fda17fd679a85bca90f/BankItems.lua#L1136


This is where GetContainerItemInfo is called, which will be null if your bank is not actually open on your character at that moment.

https://github.com/Centias/BankItems/blob/8c26ee910fd3709f5a596fda17fd679a85bca90f/BankItems.lua#L4220

To trigger it, you need to *only* have the items available for crafting in the reagent bank - it will try to take the items from your reagent bag or bank first, and won't cause this error.

I have been poking around off and on to even try and figure out what it's doing as I'm not that familiar with how the BankItems code works, and I don't think I currently have a great solution. My current hack to fix it being cleared entirely is to make BankItems_SaveReagentBank() exit out immediately if the bank is not currently open. But that means we'll need an entirely new way to handle the bagsToUpdate.rbank == true condition that involves updating the reagent bank item cache instead of relying on the data always being available, but that's a fair bit more work that requires me to better understand how the cache is used and presented (especially since the reagent bank is unique and not presented to the user like the actual reagent bank is in game, and instead as just a bunch of bags that grows and shrinks in size...)

**Comment by GTSavvy** [comment]
Before Crafting Bolt of Netherweave on Pisco (notice Netherweave Cloth is only in Reagent Bank):
![image](https://user-images.githubusercontent.com/119644994/206323182-d45d8acd-667d-4b39-95d4-d059f64b42e1.png)

After crafting Bolt of Netherweave on Pisco (notice Pisco's Netherweave Cloth data is now completely missing)
![image](https://user-images.githubusercontent.com/119644994/206323309-df5423e2-9074-44cb-bba6-a70280b7c0b7.png)

Entire Reagent Bank cache is now deleted/missing as well:
![image](https://user-images.githubusercontent.com/119644994/206323567-881e30a2-34f3-464c-a074-df612f063fab.png)

**Comment by Centias** [comment]
This is a lot of useful information. I see now what's going on, though it may take a little bit to come up with a good fix for it. Looks like I'm going to have to write in some new code blocks for updating the reagent bank totals, because it kind of skips over those since it was able to just view it and save directly before, but it should be possible.

**Comment by Centias** [comment]
After a fair bit of head scratching, and crafting like a hundred random things, I think I have it working. At the very least, the reagent bank won't get wiped out, but hopefully the saved numbers for the reagent bank should also be getting updated correctly. I should have a new version ready to download in a minute.

**Comment by GTSavvy** [comment]
Did some testing with your update and it does look like it works. Nice job!

**Comment by madar2252** [comment]
thanks for the update!
